apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-chart-release
  namespace: flux-system
spec:
  interval: 1m7s
  chart:
    spec:
      chart: my-chart
      version: '>= 0.0.1'
      sourceRef:
        kind: HelmRepository
        name: helm-gitops-example
        namespace: flux-system
      interval: 49s
  values:
    replicaCount: 2