apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-helm-app
  namespace: flux-helm
spec:
  interval: 1m
  chart:
    spec:
      chart: my-chart
      version: '>= 0.0.1'
      sourceRef:
        kind: HelmRepository
        name: helm-gitops-example
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2