apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-gitops-example
  namespace: flux-system
spec:
  interval: 1s
  url: https://davescreen.github.io/helm-gitops-example