apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-foundations
  namespace: flagger-exercise
  labels:
    app: gitops-foundations
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitops-foundations-service
              port:
                number: 80